# Historical / exploratory seed diagnostic — NOT used by any reported paper result.
#
# All paper results use the fixed seeds 42 / 123 / 777 / 2024 / 3407 with no
# outcome-based filtering (see README §9 and the --seeds default of the run_* scripts).
#
# This file is kept only as a record of an early exploration: once, 30 random seeds were
# ranked by SWA accuracy and the middle 10 were kept (dropping the 10 worst and the
# 10 best) to gauge how much the metric moves with seed choice. Because that selection
# depends on outcomes, it is deliberately not used in the paper or in any reported
# experiment — do not cite or reuse this list as a reproduction seed set.
#
# Autogenerated long ago by analyze_30seeds_trim.py (exploratory script, not released);
# kept for transparency. Do not hand-edit.
REPRO_SEEDS = [5, 28, 19, 21, 7, 20, 15, 18, 30, 3]
